---
language: node_js

node_js:
  - node
  - lts/*

dist: bionic

services:
  - docker

install:
  - npm install
  - npm install aerospike

before_script:
  - npm run aerospike

script:
  - npm run lint:dry
  - npm test
  - npm run build
